"""
Streamlit App - Wellness Tourism Package Purchase Predictor
Loads the model committed to the repository and predicts whether a prospective
customer is likely to purchase the Wellness Tourism Package.
"""
import joblib
import pandas as pd
import streamlit as st

MODEL_PATH = "tourism_project/deployment/model.joblib"

st.set_page_config(page_title="Wellness Tourism Purchase Predictor", page_icon="🧳")


@st.cache_resource
def load_model():
    return joblib.load(MODEL_PATH)


st.title("🧳 Wellness Tourism Package — Purchase Predictor")
st.write(
    "Enter a customer's details to predict whether they are likely to purchase "
    "the newly launched **Wellness Tourism Package**."
)

model = load_model()

with st.form("customer_form"):
    col1, col2 = st.columns(2)

    with col1:
        age = st.number_input("Age", min_value=18, max_value=100, value=35)
        typeof_contact = st.selectbox("Type of Contact", ["Self Enquiry", "Company Invited"])
        city_tier = st.selectbox("City Tier", [1, 2, 3])
        duration_of_pitch = st.number_input("Duration of Pitch (minutes)", 1, 180, 15)
        occupation = st.selectbox(
            "Occupation", ["Salaried", "Free Lancer", "Small Business", "Large Business"]
        )
        gender = st.selectbox("Gender", ["Male", "Female"])
        num_persons_visiting = st.number_input("Number of Persons Visiting", 1, 10, 2)
        num_followups = st.number_input("Number of Followups", 0, 20, 3)
        product_pitched = st.selectbox(
            "Product Pitched", ["Basic", "Deluxe", "Standard", "Super Deluxe", "King"]
        )
        preferred_property_star = st.selectbox("Preferred Property Star", [3.0, 4.0, 5.0])

    with col2:
        marital_status = st.selectbox("Marital Status", ["Single", "Married", "Divorced"])
        num_trips = st.number_input("Number of Trips (avg/year)", 0, 30, 3)
        passport = st.selectbox("Holds Passport?", ["Yes", "No"])
        pitch_satisfaction = st.slider("Pitch Satisfaction Score", 1, 5, 3)
        own_car = st.selectbox("Owns a Car?", ["Yes", "No"])
        num_children = st.number_input("Number of Children Visiting (<5 yrs)", 0, 5, 0)
        designation = st.selectbox(
            "Designation", ["Executive", "Manager", "Senior Manager", "AVP", "VP"]
        )
        monthly_income = st.number_input("Monthly Income", 1000, 200000, 22000)

    submitted = st.form_submit_button("Predict")

if submitted:
    input_df = pd.DataFrame([{
        "Age": age,
        "TypeofContact": typeof_contact,
        "CityTier": city_tier,
        "DurationOfPitch": duration_of_pitch,
        "Occupation": occupation,
        "Gender": gender,
        "NumberOfPersonVisiting": num_persons_visiting,
        "NumberOfFollowups": num_followups,
        "ProductPitched": product_pitched,
        "PreferredPropertyStar": preferred_property_star,
        "MaritalStatus": marital_status,
        "NumberOfTrips": num_trips,
        "Passport": 1 if passport == "Yes" else 0,
        "PitchSatisfactionScore": pitch_satisfaction,
        "OwnCar": 1 if own_car == "Yes" else 0,
        "NumberOfChildrenVisiting": num_children,
        "Designation": designation,
        "MonthlyIncome": monthly_income,
    }])

    prediction = model.predict(input_df)[0]
    probability = model.predict_proba(input_df)[0][1]

    st.subheader("Prediction Result")
    if prediction == 1:
        st.success(f"✅ Likely to PURCHASE the package (confidence: {probability:.1%})")
    else:
        st.warning(f"❌ Unlikely to purchase the package (confidence: {(1 - probability):.1%})")

    st.caption(
        "This prediction is generated by a model trained on historical customer data "
        "and is intended to support, not replace, the sales team's judgement."
    )
